# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    # image: mariadb
    image: mariadb:10.9.4    
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080